/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#561cb7",
        "on-surface-variant": "#4a4454",
        "inverse-on-surface": "#ebf1ff",
        "secondary-container": "#ffac52",
        "tertiary-container": "#815dd9",
        "on-surface": "#111c2c",
        "surface-tint": "#6e3dd0",
        "outline": "#7b7485",
        "on-tertiary-fixed-variant": "#522aa7",
        "surface-container": "#e7eeff",
        "on-tertiary-container": "#fffbff",
        "surface-dim": "#cfdaf1",
        "secondary-fixed": "#ffdcbd",
        "on-primary-container": "#fffbff",
        "surface-variant": "#d8e3fa",
        "tertiary-fixed": "#e9ddff",
        "background": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "on-secondary-fixed-variant": "#693c00",
        "surface": "#f9f9ff",
        "on-primary": "#ffffff",
        "secondary": "#8a5100",
        "tertiary": "#6843be",
        "on-secondary-fixed": "#2c1600",
        "on-primary-fixed": "#24005b",
        "primary-fixed-dim": "#d1bcff",
        "on-tertiary-fixed": "#23005c",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-container-highest": "#d8e3fa",
        "on-background": "#111c2c",
        "inverse-primary": "#d1bcff",
        "secondary-fixed-dim": "#ffb86f",
        "tertiary-fixed-dim": "#d0bcff",
        "outline-variant": "#ccc3d6",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "inverse-surface": "#263142",
        "on-secondary-container": "#724100",
        "primary": "#6c3acd",
        "primary-fixed": "#eaddff",
        "primary-container": "#8557e8",
        "on-error-container": "#93000a",
        "surface-container-high": "#dee8ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "base-unit": "8px",
        "margin-mobile": "16px",
        "container-max-width": "1280px",
        "gutter": "24px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Lexend"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Lexend"],
        "body-lg": ["Lexend"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
